namespace CopDocs;

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Generates the cop-reference.html file from extracted package data.
/// </summary>
public class HtmlGenerator
{
    public void Generate(ReferenceData data, string outputPath)
    {
        using var writer = new StreamWriter(outputPath, false, System.Text.Encoding.UTF8);
        writer.NewLine = "\n";

        writer.Write(Header.ReplaceLineEndings("\n"));
        writer.Write("\n");

        // Categories
        writer.Write("// === PACKAGE DATA (generated by copdocs) ===\n");
        writer.Write("const categories = ");
        var catOptions = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
        writer.Write(JsonSerializer.Serialize(data.Categories, catOptions));
        writer.Write(";\n\n");

        // Packages
        writer.Write("const packages = ");
        var pkgOptions = new JsonSerializerOptions
        {
            WriteIndented = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        };
        writer.Write(JsonSerializer.Serialize(data.Packages, pkgOptions));
        writer.Write(";\n");

        writer.Write(Footer.ReplaceLineEndings("\n"));
    }

    private const string Header = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cop Package Reference</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; display: flex; height: 100vh; color: #24292f; }

/* Sidebar */
.sidebar { width: 320px; border-right: 1px solid #d0d7de; overflow-y: auto; background: #f6f8fa; padding: 12px 0; flex-shrink: 0; }
.sidebar h2 { padding: 8px 16px; font-size: 14px; color: #57606a; text-transform: uppercase; letter-spacing: 0.5px; cursor: pointer; }
.sidebar h2:hover { color: #0969da; }
.tree-node { cursor: pointer; user-select: none; }
.tree-label { display: flex; align-items: center; padding: 4px 16px; font-size: 13px; border-radius: 6px; margin: 1px 8px; }
.tree-label:hover { background: #eaeef2; }
.tree-label.active { background: #ddf4ff; color: #0969da; font-weight: 600; }
.tree-toggle { width: 16px; font-size: 10px; color: #57606a; flex-shrink: 0; }
.tree-icon { margin-right: 6px; font-size: 12px; }
.tree-children { padding-left: 16px; }
.tree-children.collapsed { display: none; }
.category-label { font-size: 11px; font-weight: 700; text-transform: uppercase; color: #57606a; letter-spacing: 0.5px; padding: 12px 16px 4px; cursor: pointer; display: flex; align-items: center; gap: 4px; }
.category-label:hover { color: #0969da; }
.category-label .tree-toggle { font-size: 10px; }
.category-children { padding-left: 0; }
.category-children.collapsed { display: none; }

/* Main content */
.main { flex: 1; overflow-y: auto; padding: 32px 48px; max-width: 960px; }
.main h1 { font-size: 24px; margin-bottom: 8px; }
.main h2 { font-size: 18px; margin: 24px 0 12px; padding-bottom: 6px; border-bottom: 1px solid #d0d7de; }
.main h3 { font-size: 15px; margin: 16px 0 8px; }

/* Property row */
.prop-row { display: flex; align-items: center; padding: 5px 8px; border-bottom: 1px solid #f0f0f0; font-size: 13px; }
.prop-row:hover { background: #f6f8fa; }
.type-overview { margin: 12px 0 16px; padding: 12px 16px; background: #f6f8fa; border-radius: 6px; font-size: 13px; line-height: 1.6; color: #24292f; }
.type-overview code { background: #eff1f3; padding: 2px 5px; border-radius: 3px; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; }
.type-overview pre { background: #24292f; color: #e6edf3; padding: 12px 16px; border-radius: 6px; margin: 8px 0; overflow-x: auto; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; line-height: 1.5; }
.prop-name { font-family: 'SFMono-Regular', Consolas, monospace; font-weight: 600; width: 200px; flex-shrink: 0; }
.prop-type { color: #6639ba; width: 180px; flex-shrink: 0; font-family: monospace; font-size: 12px; }
.prop-type a.type-nav-link { color: #6639ba; text-decoration: none; border-bottom: 1px dotted #6639ba; }
.prop-type a.type-nav-link:hover { color: #8250df; border-bottom-style: solid; }
.prop-desc { flex: 1; color: #57606a; }

/* Item row (for predicates, functions, checks) */
.item-row { display: flex; align-items: center; padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 13px; }
.item-row:hover { background: #f6f8fa; }
.item-name { font-family: 'SFMono-Regular', Consolas, monospace; font-weight: 600; flex: 1; }
.item-type { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; color: #8250df; margin-left: 8px; flex-shrink: 0; }
.item-type a.type-nav-link { color: #8250df; text-decoration: none; border-bottom: 1px dotted #8250df; }
.item-type a.type-nav-link:hover { color: #6639ba; border-bottom-style: solid; }
.item-detail { color: #57606a; font-size: 12px; margin-left: 12px; }

/* Function block (signature on one line, description below) */
.fn-block { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 13px; }
.fn-block:hover { background: #f6f8fa; }
.fn-signature { display: flex; align-items: center; }
.fn-desc { color: #57606a; font-size: 12px; margin-top: 3px; padding-left: 2px; }
.source-link { font-size: 11px; color: #57606a; text-decoration: none; margin-left: 8px; opacity: 0.4; transition: opacity 0.2s; flex-shrink: 0; }
.source-link:hover { opacity: 1; color: #0969da; }
.item-type-inline { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; color: #8250df; }
.item-type-inline a.type-nav-link { color: #8250df; text-decoration: none; border-bottom: 1px dotted #8250df; }
.item-type-inline a.type-nav-link:hover { color: #6639ba; border-bottom-style: solid; }

/* Comment button and input */
.comment-btn { cursor: pointer; font-size: 14px; margin-left: 8px; opacity: 0.3; transition: opacity 0.2s; flex-shrink: 0; }
.comment-btn:hover { opacity: 1; }
.comment-btn.has-comment { opacity: 1; color: #0969da; }
.comment-input { display: none; width: 100%; margin-top: 4px; padding: 6px 8px; border: 1px solid #d0d7de; border-radius: 6px; font-size: 12px; font-family: inherit; resize: vertical; min-height: 28px; }
.comment-input.visible { display: block; }
.comment-wrapper { width: 100%; }

/* Toolbar */
.toolbar { position: fixed; top: 12px; right: 24px; display: flex; gap: 8px; z-index: 100; }
.toolbar button { padding: 6px 14px; border: 1px solid #d0d7de; border-radius: 6px; background: #fff; cursor: pointer; font-size: 13px; font-weight: 500; }
.toolbar button:hover { background: #f3f4f6; }
.toolbar button.primary { background: #2da44e; color: #fff; border-color: #2da44e; }
.toolbar button.primary:hover { background: #2c974b; }
.badge { background: #0969da; color: #fff; border-radius: 10px; padding: 1px 6px; font-size: 11px; margin-left: 4px; }

/* Collection header */
.collection-header { display: flex; align-items: center; padding: 5px 8px; background: #f6f8fa; border-bottom: 1px solid #eaeef2; font-size: 13px; font-weight: 600; }

/* Section tag */
.section-tag { display: inline-block; padding: 1px 6px; border-radius: 4px; font-size: 11px; font-weight: 600; margin-right: 6px; }
.tag-type { background: #ddf4ff; color: #0969da; }
.tag-predicate { background: #fff8c5; color: #9a6700; }
.tag-function { background: #dcffe4; color: #1a7f37; }
.tag-check { background: #ffebe9; color: #cf222e; }
.tag-command { background: #fbefff; color: #8250df; }
.tag-enum { background: #fff1e5; color: #bc4c00; }
.enum-values { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 6px; padding-left: 2px; }
.enum-value { display: inline-block; padding: 2px 8px; background: #fff1e5; color: #bc4c00; border-radius: 4px; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; }

/* Package overview */
.pkg-overview { margin: 8px 0 20px; font-size: 14px; line-height: 1.6; color: #24292f; }
.pkg-sample { margin: 16px 0; }
.pkg-sample h3 { font-size: 14px; margin-bottom: 8px; color: #24292f; }
.pkg-sample .code-block { position: relative; }
.pkg-sample .code-block pre { background: #24292f; color: #e6edf3; padding: 16px 20px; border-radius: 8px; overflow-x: auto; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 13px; line-height: 1.6; margin: 0; }
.pkg-sample .copy-btn { position: absolute; top: 8px; right: 8px; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.2); color: #e6edf3; border-radius: 6px; padding: 4px 8px; font-size: 12px; cursor: pointer; opacity: 0; transition: opacity 0.15s; }
.pkg-sample .code-block:hover .copy-btn { opacity: 1; }
.pkg-sample .copy-btn:hover { background: rgba(255,255,255,0.2); }
.pkg-sample .copy-btn.copied { color: #3fb950; }
.pkg-exports { display: flex; flex-wrap: wrap; gap: 8px; margin: 20px 0; }
.pkg-exports a { display: inline-flex; align-items: center; gap: 4px; padding: 6px 14px; border-radius: 6px; font-size: 13px; font-weight: 500; text-decoration: none; cursor: pointer; border: 1px solid #d0d7de; }
.pkg-exports a:hover { background: #f6f8fa; }
.pkg-exports .count { font-weight: 700; }

/* Syntax highlighting */
.cop-kw { color: #ff7b72; font-weight: 600; }
.cop-str { color: #a5d6ff; }
.cop-comment { color: #8b949e; font-style: italic; line-height: 0; vertical-align: baseline; }
.cop-template { color: #ffa657; }
.cop-pred { color: #d2a8ff; }
.cop-num { color: #79c0ff; }
.cop-op { color: #ff7b72; }
.cop-type { color: #7ee787; }
.cop-fn { color: #d2a8ff; }
</style>
</head>
<body>

<div class="sidebar">
  <h2 onclick="showHome()">Packages</h2>
  <div id="tree"></div>
</div>

<div class="main" id="content">
  <h1>Cop Package Reference</h1>
  <div class="type-overview">
    <p><strong>Agent Cop</strong> is a static analysis tool that detects code slop &mdash; architectural violations, convention drift, and design debt that coding agents introduce at machine speed.</p>
    <p style="margin-top:8px;">Rules are expressed in a simple DSL and enforced deterministically in CI. Example:</p>
    <pre id="home-sample"></pre>
    <p style="margin-top:12px;">Browse the package tree on the left to explore available types, predicates, functions, and commands.</p>
  </div>
</div>

<div class="toolbar">
  <button onclick="submitToCopilot()" class="primary">Copy Comments to Clipboard <span class="badge" id="commentCount">0</span></button>
</div>

<script>
""";

    private const string Footer = """

// === STATE ===
let comments = JSON.parse(localStorage.getItem('cop-review-comments') || '{}');
let activeNode = null;

// === TREE RENDERING ===
function buildTree() {
  const tree = document.getElementById('tree');
  tree.innerHTML = '';

  for (const cat of categories) {
    const catDiv = document.createElement('div');
    catDiv.className = 'tree-category';
    const isCore = cat.name === 'Core';
    catDiv.innerHTML = `
      <div class="category-label" data-category="${cat.name}">
        <span class="tree-toggle">${isCore ? '▼' : '▶'}</span>
        ${cat.name}
      </div>
      <div class="category-children${isCore ? '' : ' collapsed'}"></div>
    `;
    const catChildrenDiv = catDiv.querySelector('.category-children');

    // Category label click toggles collapse
    catDiv.querySelector('.category-label').addEventListener('click', (e) => {
      const children = catDiv.querySelector('.category-children');
      const toggle = catDiv.querySelector('.category-label .tree-toggle');
      children.classList.toggle('collapsed');
      toggle.textContent = children.classList.contains('collapsed') ? '▶' : '▼';
    });

    for (const pkgId of cat.packages) {
      const pkg = packages[pkgId];
      if (!pkg) continue;
      const pkgNode = document.createElement('div');
      pkgNode.className = 'tree-node';

      const hasTypes = pkg.types && Object.keys(pkg.types).length > 0;
      const hasPreds = pkg.predicates && pkg.predicates.filter(p => !hasTypePage(p)).length > 0;
      const hasFuncs = pkg.functions && pkg.functions.filter(f => !hasTypePage(f)).length > 0;
      const hasFuncsOrPreds = hasFuncs || hasPreds;
      const hasChecks = pkg.checks && pkg.checks.length > 0;
      const hasCmds = pkg.commands && pkg.commands.length > 0;
      const hasEnums = pkg.enums && pkg.enums.length > 0;

      pkgNode.innerHTML = `
        <div class="tree-label" data-pkg="${pkgId}">
          <span class="tree-toggle">▶</span>
          <span class="tree-icon">📦</span>
          <span>${pkg.label}</span>
        </div>
        <div class="tree-children collapsed"></div>
      `;
      const childrenDiv = pkgNode.querySelector('.tree-children');

      if (hasTypes || hasEnums) {
        const secNode = document.createElement('div');
        secNode.className = 'tree-node';
        secNode.innerHTML = `
          <div class="tree-label" data-pkg="${pkgId}" data-section="types-header">
            <span class="tree-toggle">▶</span>
            <span class="section-tag tag-type">T</span>
            <span>Types</span>
          </div>
          <div class="tree-children collapsed"></div>
        `;
        const typesChildren = secNode.querySelector('.tree-children');
        if (hasTypes) {
          for (const typeName of Object.keys(pkg.types).sort()) {
            const typeNode = document.createElement('div');
            typeNode.className = 'tree-node';
            const traitBadge = pkg.types[typeName].isTrait ? ' <span style="color:#0969da; font-size:10px; opacity:0.8;">(trait)</span>' : '';
            typeNode.innerHTML = `
              <div class="tree-label" data-pkg="${pkgId}" data-type="${typeName}">
                <span class="tree-toggle" style="visibility:hidden"></span>
                <span class="tree-icon">◆</span>
                <span>${typeName}${traitBadge}</span>
              </div>
            `;
            typesChildren.appendChild(typeNode);
          }
        }
        if (hasEnums) {
          for (const en of pkg.enums) {
            const enumNode = document.createElement('div');
            enumNode.className = 'tree-node';
            enumNode.innerHTML = `
              <div class="tree-label" data-pkg="${pkgId}" data-view="enums" data-enum="${en.name}">
                <span class="tree-toggle" style="visibility:hidden"></span>
                <span class="tree-icon">◇</span>
                <span>${en.name}</span>
              </div>
            `;
            typesChildren.appendChild(enumNode);
          }
        }
        childrenDiv.appendChild(secNode);
      }

      if (hasFuncsOrPreds) {
        const fnCount = pkg.functions ? pkg.functions.filter(f => !hasTypePage(f)).length : 0;
        const predCount = pkg.predicates ? pkg.predicates.filter(p => !hasTypePage(p)).length : 0;
        const totalCount = fnCount + predCount;
        const secNode = document.createElement('div');
        secNode.className = 'tree-node';
        secNode.innerHTML = `
          <div class="tree-label" data-pkg="${pkgId}" data-view="functions">
            <span class="tree-toggle" style="visibility:hidden"></span>
            <span class="section-tag tag-function">F</span>
            <span>Functions (${totalCount})</span>
          </div>
        `;
        childrenDiv.appendChild(secNode);
      }

      if (hasChecks) {
        const secNode = document.createElement('div');
        secNode.className = 'tree-node';
        secNode.innerHTML = `
          <div class="tree-label" data-pkg="${pkgId}" data-view="checks">
            <span class="tree-toggle" style="visibility:hidden"></span>
            <span class="section-tag tag-check">C</span>
            <span>Checks (${pkg.checks.length})</span>
          </div>
        `;
        childrenDiv.appendChild(secNode);
      }

      if (hasCmds) {
        const secNode = document.createElement('div');
        secNode.className = 'tree-node';
        secNode.innerHTML = `
          <div class="tree-label" data-pkg="${pkgId}" data-view="commands">
            <span class="tree-toggle" style="visibility:hidden"></span>
            <span class="section-tag tag-command">!</span>
            <span>Commands (${pkg.commands.length})</span>
          </div>
        `;
        childrenDiv.appendChild(secNode);
      }

      catChildrenDiv.appendChild(pkgNode);
    }
    tree.appendChild(catDiv);
  }

  // Event delegation
  tree.addEventListener('click', (e) => {
    const label = e.target.closest('.tree-label');
    if (!label) return;
    const pkg = label.dataset.pkg;
    const type = label.dataset.type;
    const view = label.dataset.view;
    const section = label.dataset.section;

    if (type) {
      document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));
      label.classList.add('active');
      renderType(pkg, type);
      location.hash = `${pkg}/${type}`;
      // Ensure parent package node is expanded
      ensurePackageExpanded(pkg);
    } else if (view) {
      document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));
      label.classList.add('active');
      if (view === 'predicates') renderFunctions(pkg);
      else if (view === 'functions') renderFunctions(pkg);
      else if (view === 'checks') renderChecks(pkg);
      else if (view === 'commands') renderCommands(pkg);
      else if (view === 'enums') renderEnums(pkg);
      else if (view === 'exports') renderFunctions(pkg);
      location.hash = `${pkg}/${view}`;
      // Ensure parent package node is expanded
      ensurePackageExpanded(pkg);
    } else if (section) {
      // Toggle section expand
      const children = label.nextElementSibling;
      const toggle = label.querySelector('.tree-toggle');
      if (children) {
        children.classList.toggle('collapsed');
        toggle.textContent = children.classList.contains('collapsed') ? '▶' : '▼';
      }
    } else {
      // Show package overview + toggle expand/collapse
      document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));
      label.classList.add('active');
      renderPackageOverview(pkg);
      location.hash = pkg;
      const children = label.nextElementSibling;
      const toggle = label.querySelector('.tree-toggle');
      if (children) {
        children.classList.toggle('collapsed');
        toggle.textContent = children.classList.contains('collapsed') ? '▶' : '▼';
      }
    }
  });
}

// Ensure a package node in the tree is expanded (not collapsed)
function ensurePackageExpanded(pkgId) {
  const pkgLabel = document.querySelector(`.tree-label[data-pkg="${pkgId}"]:not([data-type]):not([data-view]):not([data-section])`);
  if (!pkgLabel) return;
  const children = pkgLabel.nextElementSibling;
  const toggle = pkgLabel.querySelector('.tree-toggle');
  if (children && children.classList.contains('collapsed')) {
    children.classList.remove('collapsed');
    if (toggle) toggle.textContent = '▼';
  }
}

// === CONTENT RENDERING ===
function renderPackageOverview(pkgId) {
  const pkg = packages[pkgId];
  const content = document.getElementById('content');

  let html = `<h1>📦 ${pkg.label}</h1>`;

  if (pkg.overview) {
    html += `<div class="pkg-overview">${pkg.overview}</div>`;
  }

  // Export summary
  const typeCount = pkg.types ? Object.keys(pkg.types).length : 0;
  const predCount = pkg.predicates ? pkg.predicates.length : 0;
  const funcCount = pkg.functions ? pkg.functions.length : 0;
  const combinedFuncCount = predCount + funcCount;
  const checkCount = pkg.checks ? pkg.checks.length : 0;
  const cmdCount = pkg.commands ? pkg.commands.length : 0;
  const enumCount = pkg.enums ? pkg.enums.length : 0;

  html += `<div class="pkg-exports">`;
  if (typeCount > 0) html += `<a onclick="navToSection('${pkgId}','types-header')"><span class="section-tag tag-type">T</span> <span class="count">${typeCount}</span> types</a>`;
  if (enumCount > 0) html += `<a onclick="navToSection('${pkgId}','types-header')"><span class="section-tag tag-enum">◇</span> <span class="count">${enumCount}</span> enums</a>`;
  if (combinedFuncCount > 0) html += `<a onclick="navToSection('${pkgId}','functions')"><span class="section-tag tag-function">F</span> <span class="count">${combinedFuncCount}</span> functions</a>`;
  if (checkCount > 0) html += `<a onclick="navToSection('${pkgId}','checks')"><span class="section-tag tag-check">C</span> <span class="count">${checkCount}</span> checks</a>`;
  if (cmdCount > 0) html += `<a onclick="navToSection('${pkgId}','commands')"><span class="section-tag tag-command">!</span> <span class="count">${cmdCount}</span> commands</a>`;
  html += `</div>`;

  // Code samples
  if (pkg.samples && pkg.samples.length > 0) {
    html += `<h2>Getting Started</h2>`;
    for (const sample of pkg.samples) {
      html += `<div class="pkg-sample">`;
      html += `<h3>${escapeHtml(sample.title)}</h3>`;
      html += `<div class="code-block"><pre>${highlightCop(sample.code)}</pre><button class="copy-btn" onclick="copySample(this)">Copy</button></div>`;
      html += `</div>`;
    }
  }

  content.innerHTML = html;
}

function navToSection(pkgId, view) {
  const selector = view === 'types-header'
    ? `.tree-label[data-pkg="${pkgId}"][data-section="types-header"]`
    : `.tree-label[data-pkg="${pkgId}"][data-view="${view}"]`;
  const label = document.querySelector(selector);
  if (label) {
    label.click();
    label.scrollIntoView({ block: 'nearest' });
  }
}

function renderType(pkgId, typeName) {
  const pkg = packages[pkgId];
  const type = pkg.types[typeName];
  const content = document.getElementById('content');

  let html = `<h1>${pkg.label} <span style="color:#57606a; font-weight:400">›</span> ${typeName}${sourceLink(type.sourceUrl)}</h1>`;
  if (type.isTrait) {
    html += `<span style="display:inline-block; background:#ddf4ff; color:#0969da; border-radius:12px; padding:2px 10px; font-size:12px; font-weight:500; margin-bottom:8px;">trait</span>`;
  }
  // Show type definition with inheritance chain (C#-style: type Name : Base, Traits)
  const chain = [];
  if (type.baseType) chain.push(type.baseType);
  if (type.traits && type.traits.length > 0) chain.push(...type.traits);
  if (chain.length > 0) {
    html += `<pre style="background:#f6f8fa; border:1px solid #d0d7de; border-radius:6px; padding:12px 16px; font-size:14px; margin:8px 0 12px;"><code>type <strong>${typeName}</strong> : ${chain.join(', ')}</code></pre>`;
  }
  if (type.desc) {
    html += `<div class="type-overview">${type.desc}</div>`;
  }
  if (type.conformers && type.conformers.length > 0) {
    html += `<p style="color:#57606a; font-size:13px; margin-top:4px;">Conforming types: <code>${type.conformers.join('</code>, <code>')}</code></p>`;
  }
  if (pkg.collections && pkg.collections.length > 0) {
    const names = pkg.collections.map(c => typeof c === 'string' ? c : c.name);
    html += `<p style="color:#57606a; font-size:13px; margin-top:4px;">Functions: <code>${names.join('</code>, <code>')}</code></p>`;
  }
  if (type.props.length > 0) {
    html += `<h2>${type.isTrait ? 'Members' : 'Properties'}</h2>`;
  }

  for (const prop of type.props) {
    const key = `${pkgId}.${typeName}.${prop.name}`;
    const hasComment = comments[key] ? 'has-comment' : '';
    html += `
      <div class="comment-wrapper">
        <div class="prop-row">
          <span class="prop-name">${prop.name}</span>
          <span class="prop-type">${formatTypeLink(pkgId, prop.type)}</span>
          <span class="prop-desc">${escapeHtml(prop.desc)}</span>
          <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
        </div>
        <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
      </div>
    `;
  }

  // Collect predicates that apply to this type from all packages
  const applicablePredicates = [];
  for (const [pId, p] of Object.entries(packages)) {
    if (!p.predicates) continue;
    for (const pred of p.predicates) {
      if (pred.appliesTo === typeName) {
        applicablePredicates.push({ ...pred, fromPkg: pId });
      }
    }
  }

  if (applicablePredicates.length > 0) {
    html += `<h2>Predicates</h2>`;
    for (const pred of applicablePredicates.sort((a,b) => a.name.localeCompare(b.name))) {
      const key = `${pred.fromPkg}.pred.${pred.name}.${pred.appliesTo}`;
      const hasComment = comments[key] ? 'has-comment' : '';
      const fromLabel = pred.fromPkg !== pkgId ? ` <span style="color:#8b949e; font-size:11px;">(${pred.fromPkg})</span>` : '';
      const paramsHtml = pred.params ? `(${formatParamsWithLinks(pkgId, pred.params)})` : '';
      html += `
        <div class="comment-wrapper">
          <div class="item-row">
            <span class="item-name">${pred.name}${paramsHtml}${fromLabel}</span>
            <span class="item-detail">${escapeHtml(pred.desc)}</span>
            ${sourceLink(pred.sourceUrl)}
            <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
          </div>
          <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
        </div>
      `;
    }
  }

  // Collect functions that apply to this type from all packages
  const applicableFunctions = [];
  for (const [fPkgId, fPkg] of Object.entries(packages)) {
    if (!fPkg.functions) continue;
    for (const fn of fPkg.functions) {
      if (fn.appliesTo === typeName) {
        applicableFunctions.push({ ...fn, fromPkg: fPkgId });
      }
    }
  }

  if (applicableFunctions.length > 0) {
    html += `<h2>Functions</h2>`;
    for (const fn of applicableFunctions.sort((a,b) => a.name.localeCompare(b.name))) {
      const key = `${fn.fromPkg}.fn.${fn.name}.${(fn.params||'').replace(/[, ]/g, '_')}`;
      const hasComment = comments[key] ? 'has-comment' : '';
      const fromLabel = fn.fromPkg !== pkgId ? ` <span style="color:#8b949e; font-size:11px;">(${fn.fromPkg})</span>` : '';
      const remainingParams = fn.params.includes(',') ? fn.params.substring(fn.params.indexOf(',') + 1).trim() : '';
      const paramsHtml = remainingParams ? formatParamsWithLinks(pkgId, remainingParams) : '';
      const returnsHtml = fn.returns ? ` → ${formatTypeLink(pkgId, fn.returns)}` : '';
      html += `
        <div class="comment-wrapper">
          <div class="fn-block">
            <div class="fn-signature">
              <span class="item-name">${fn.name}(${paramsHtml})${returnsHtml}${fromLabel}</span>
              ${sourceLink(fn.sourceUrl)}
              <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
            </div>
            <div class="fn-desc">${escapeHtml(fn.desc)}</div>
          </div>
          <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
        </div>
      `;
    }
  }

  content.innerHTML = html;
  wireUpComments(content);
  wireUpTypeLinks(content);
}

function renderPredicates(pkgId) {
  const pkg = packages[pkgId];
  const content = document.getElementById('content');

  let html = `<h1>${pkg.label} <span style="color:#57606a; font-weight:400">›</span> Predicates</h1>`;
  html += `<p style="color:#57606a; font-size:13px; margin-top:4px; margin-bottom:16px;">${pkg.predicates.length} exported predicates</p>`;

  // Group by appliesTo
  const groups = {};
  for (const p of pkg.predicates) {
    if (!groups[p.appliesTo]) groups[p.appliesTo] = [];
    groups[p.appliesTo].push(p);
  }

  for (const [appliesTo, preds] of Object.entries(groups).sort(([a],[b]) => a.localeCompare(b))) {
    html += `<h3>On ${appliesTo}</h3>`;
    for (const pred of preds.sort((a,b) => a.name.localeCompare(b.name))) {
      const key = `${pkgId}.pred.${pred.name}.${pred.appliesTo}`;
      const hasComment = comments[key] ? 'has-comment' : '';
      const paramsHtml = pred.params ? `, ${formatParamsWithLinks(pkgId, pred.params)}` : '';
      html += `
        <div class="comment-wrapper">
          <div class="item-row">
            <span class="item-name">${pred.name}(${formatTypeLink(pkgId, pred.appliesTo)}${paramsHtml})</span>
            <span class="item-detail">${escapeHtml(pred.desc)}</span>
            ${sourceLink(pred.sourceUrl)}
            <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
          </div>
          <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
        </div>
      `;
    }
  }

  content.innerHTML = html;
  wireUpComments(content);
}

function renderFunctions(pkgId) {
  const pkg = packages[pkgId];
  const standaloneFns = (pkg.functions || []).filter(f => !hasTypePage(f));

  // Convert standalone predicates to function-like entries
  const standalonePreds = (pkg.predicates || []).filter(p => !hasTypePage(p)).map(p => ({
    name: p.name,
    params: p.appliesTo + (p.params ? ', ' + p.params : ''),
    returns: 'bool',
    desc: p.desc || '',
    sourceUrl: p.sourceUrl
  }));

  const allItems = [...standaloneFns, ...standalonePreds];
  renderCallables(pkgId, allItems, 'Functions', 'fn');
}

function renderCallables(pkgId, items, sectionTitle, keyPrefix) {
  const pkg = packages[pkgId];
  const content = document.getElementById('content');

  let html = `<h1>${pkg.label} <span style="color:#57606a; font-weight:400">›</span> ${sectionTitle}</h1>`;
  html += `<p style="color:#57606a; font-size:13px; margin-top:4px; margin-bottom:16px;">${items.length} exported ${sectionTitle.toLowerCase()}</p>`;

  for (const fn of items.slice().sort((a,b) => a.name.localeCompare(b.name))) {
    const key = `${pkgId}.${keyPrefix}.${fn.name}.${(fn.params||'').replace(/[, ]/g, '_')}`;
    const hasComment = comments[key] ? 'has-comment' : '';
    const paramsHtml = fn.params ? formatParamsWithLinks(pkgId, fn.params) : '';
    const returnsHtml = fn.returns ? ` → ${formatTypeLink(pkgId, fn.returns)}` : '';
    html += `
      <div class="comment-wrapper">
        <div class="fn-block">
          <div class="fn-signature">
            <span class="item-name">${fn.name}(${paramsHtml})${returnsHtml}</span>
            ${sourceLink(fn.sourceUrl)}
            <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
          </div>
          <div class="fn-desc">${escapeHtml(fn.desc)}</div>
        </div>
        <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
      </div>
    `;
  }

  content.innerHTML = html;
  wireUpComments(content);
  wireUpTypeLinks(content);
}

function renderChecks(pkgId) {
  const pkg = packages[pkgId];
  const content = document.getElementById('content');

  let html = `<h1>${pkg.label} <span style="color:#57606a; font-weight:400">›</span> Checks</h1>`;
  html += `<p style="color:#57606a; font-size:13px; margin-top:4px; margin-bottom:16px;">${pkg.checks.length} exported checks</p>`;

  for (const check of pkg.checks.slice().sort((a,b) => a.name.localeCompare(b.name))) {
    const key = `${pkgId}.check.${check.name}`;
    const hasComment = comments[key] ? 'has-comment' : '';
    html += `
      <div class="comment-wrapper">
        <div class="item-row">
          <span class="item-name">${check.name}</span>
          <span class="item-detail">${escapeHtml(check.desc)}</span>
          ${sourceLink(check.sourceUrl)}
          <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
        </div>
        <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
      </div>
    `;
  }

  content.innerHTML = html;
  wireUpComments(content);
}

function renderCommands(pkgId) {
  renderCallables(pkgId, packages[pkgId].commands, 'Commands', 'cmd');
}

function renderEnums(pkgId) {
  const pkg = packages[pkgId];
  const content = document.getElementById('content');

  let html = `<h1>${pkg.label} <span style="color:#57606a; font-weight:400">›</span> Enums</h1>`;
  html += `<p style="color:#57606a; font-size:13px; margin-top:4px; margin-bottom:16px;">${pkg.enums.length} exported enums — extensible string-valued constants for tooling and completion</p>`;

  for (const enumItem of pkg.enums.slice().sort((a,b) => a.name.localeCompare(b.name))) {
    const key = `${pkgId}.enum.${enumItem.name}`;
    const hasComment = comments[key] ? 'has-comment' : '';
    const values = enumItem.values.split('|');
    html += `
      <div class="comment-wrapper">
        <div class="fn-block">
          <div class="fn-signature">
            <span class="item-name">${enumItem.name}</span>
            ${sourceLink(enumItem.sourceUrl)}
            <span class="comment-btn ${hasComment}" data-key="${key}" title="Add comment">💬</span>
          </div>
          <div class="enum-values">${values.map(v => `<span class="enum-value">${escapeHtml(v)}</span>`).join('')}</div>
        </div>
        <textarea class="comment-input ${comments[key] ? 'visible' : ''}" data-key="${key}" placeholder="Add comment...">${comments[key] || ''}</textarea>
      </div>
    `;
  }

  content.innerHTML = html;
  wireUpComments(content);
}

function wireUpComments(container) {
  container.querySelectorAll('.comment-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const key = btn.dataset.key;
      const input = container.querySelector(`.comment-input[data-key="${CSS.escape(key)}"]`);
      input.classList.toggle('visible');
      if (input.classList.contains('visible')) input.focus();
    });
  });

  container.querySelectorAll('.comment-input').forEach(input => {
    input.addEventListener('input', () => {
      const key = input.dataset.key;
      const btn = container.querySelector(`.comment-btn[data-key="${CSS.escape(key)}"]`);
      if (input.value.trim()) {
        comments[key] = input.value.trim();
        btn.classList.add('has-comment');
      } else {
        delete comments[key];
        btn.classList.remove('has-comment');
      }
      saveComments();
      updateBadge();
    });
  });
}

// === COMMENTS ===
function saveComments() {
  localStorage.setItem('cop-review-comments', JSON.stringify(comments));
}

function updateBadge() {
  document.getElementById('commentCount').textContent = Object.keys(comments).length;
}

function submitToCopilot() {
  const keys = Object.keys(comments);
  if (keys.length === 0) {
    alert('No comments to submit.');
    return;
  }

  // Group comments by package
  const grouped = {};
  for (const [key, value] of Object.entries(comments)) {
    const parts = key.split('.');
    const pkg = parts[0];
    if (!grouped[pkg]) grouped[pkg] = [];
    const itemPath = parts.slice(1).join('.');
    grouped[pkg].push({ item: itemPath, comment: value });
  }

  // Build a prompt for Copilot CLI
  let prompt = `Process these ${keys.length} review comment(s) from the cop review app. `;
  prompt += `Each comment is an actionable request to rename, remove, or fix an API in the corresponding .cop package file.\n\n`;

  for (const [pkg, items] of Object.entries(grouped)) {
    prompt += `## ${pkg}\n`;
    for (const item of items) {
      prompt += `- ${item.item}: ${item.comment}\n`;
    }
    prompt += '\n';
  }

  navigator.clipboard.writeText(prompt).then(() => {
    // Auto-clear after successful copy
    comments = {};
    saveComments();
    updateBadge();
    alert(`Copied ${keys.length} comment(s) to clipboard and cleared queue.\nPaste into Copilot CLI.`);
    const active = document.querySelector('.tree-label.active');
    if (active) active.click();
  }).catch(() => {
    const ta = document.createElement('textarea');
    ta.value = prompt;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    comments = {};
    saveComments();
    updateBadge();
    alert(`Copied ${keys.length} comment(s) to clipboard and cleared queue.\nPaste into Copilot CLI.`);
  });
}

function formatParamsWithLinks(currentPkgId, paramsStr) {
  if (!paramsStr) return '';
  // Split params by comma, link type references in each segment
  return paramsStr.split(',').map(p => {
    p = p.trim();
    // Match patterns like "name: Type?" or "[Type]?" or just "Type"
    const colonMatch = p.match(/^(\w+):\s*(.+)$/);
    if (colonMatch) {
      return `${escapeHtml(colonMatch[1])}: ${formatTypeLink(currentPkgId, colonMatch[2])}`;
    }
    return formatTypeLink(currentPkgId, p);
  }).join(', ');
}

function formatTypeLink(currentPkgId, typeStr) {
  // First check if the exact string is a registered type (e.g. "[T]")
  const exactLink = makeTypeLink(currentPkgId, typeStr);
  if (exactLink !== typeStr) return exactLink;
  // Handle nullable collection types like [Statement]?
  const nullCollMatch = typeStr.match(/^\[(.+)\]\?$/);
  if (nullCollMatch) {
    const inner = nullCollMatch[1];
    const link = makeTypeLink(currentPkgId, inner);
    return `[${link}]?`;
  }
  // Handle collection types like [Statement], [Folder]
  const collMatch = typeStr.match(/^\[(.+)\]$/);
  if (collMatch) {
    const inner = collMatch[1];
    const link = makeTypeLink(currentPkgId, inner);
    return `[${link}]`;
  }
  // Handle nullable types like File?, string?
  const nullMatch = typeStr.match(/^(.+)\?$/);
  if (nullMatch) {
    const inner = nullMatch[1];
    const link = makeTypeLink(currentPkgId, inner);
    return `${link}?`;
  }
  return makeTypeLink(currentPkgId, typeStr);
}

function makeTypeLink(currentPkgId, typeName) {
  // Find which package owns this type
  for (const [pkgId, pkg] of Object.entries(packages)) {
    if (pkg.types && pkg.types[typeName]) {
      return `<a href="#" class="type-nav-link" data-pkg="${pkgId}" data-type="${typeName}">${typeName}</a>`;
    }
    // Check enums
    if (pkg.enums && pkg.enums.some(e => e.name === typeName)) {
      return `<a href="#" class="type-nav-link" data-pkg="${pkgId}" data-view="enums">${typeName}</a>`;
    }
  }
  // Not found as a navigable type — render plain
  return typeName;
}

function wireUpTypeLinks(container) {
  container.querySelectorAll('.type-nav-link').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const pkg = link.dataset.pkg;
      const type = link.dataset.type;
      const view = link.dataset.view;
      document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));
      if (view === 'enums') renderEnums(pkg);
      else renderType(pkg, type);
    });
  });
}

function highlightCop(code) {
  // Normalize line endings to avoid extra blank lines in <pre>
  code = code.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  // Escape HTML first
  code = code.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  // Comments (must come first, before other replacements interfere)
  code = code.replace(/(#[^\n]*)/g, '<span class="cop-comment">$1</span>');
  // Strings (single-quoted)
  code = code.replace(/'([^'\\]*(?:\\.[^'\\]*)*)'/g, '<span class="cop-str">\'$1\'</span>');
  // Template interpolation {item.Name} inside already-processed text
  code = code.replace(/\{([^}@]+)\}/g, '<span class="cop-template">{$1}</span>');
  // Keywords (must match tokenizer: type/collection/import/let/command/export/predicate/function/foreach/feed/flags/enum)
  code = code.replace(/\b(import|predicate|function|let|foreach|type|export|command|enum|flags|collection|feed|async)\b/g, '<span class="cop-kw">$1</span>');
  // Built-in actions (language-level uppercase commands)
  code = code.replace(/\b(PRINT|SAVE|RUN|DEBUG|ASSERT|FAIL)\b/g, '<span class="cop-kw">$1</span>');
  // Built-in functions and collection transforms
  code = code.replace(/\b(Where|Select|GroupBy|OrderBy|OrderByDescending|Sum|Average|Count|Reduce|Distinct|Min|Max|Get|File|Text|Path|Matches)\b/g, '<span class="cop-fn">$1</span>');
  // Predicate calls (:name)
  code = code.replace(/:([a-zA-Z][a-zA-Z0-9]*)/g, ':<span class="cop-pred">$1</span>');
  // Operators
  code = code.replace(/(\=&gt;|&amp;&amp;|\|\||\|&gt;)/g, '<span class="cop-op">$1</span>');
  // Numbers
  code = code.replace(/\b(\d+)\b/g, '<span class="cop-num">$1</span>');
  return code;
}

function escapeHtml(str) {
  if (!str) return '';
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Returns true if the function has a type page (i.e., appliesTo matches a defined type in some package)
// Generic collection functions ([T]) should appear in both the Functions section and the [T] type page
function hasTypePage(fn) {
  if (!fn.appliesTo) return false;
  // [T] is the universal collection type — don't hide these from Functions
  if (fn.appliesTo === '[T]') return false;
  for (const p of Object.values(packages)) {
    if (p.types && p.types[fn.appliesTo]) return true;
  }
  return false;
}

function sourceLink(url) {
  if (!url) return '';
  return `<a href="${url}" target="_blank" class="source-link" title="View source">📄</a>`;
}

function copySample(btn) {
  var pre = btn.previousElementSibling;
  var text = pre.textContent;
  navigator.clipboard.writeText(text).then(function() {
    btn.textContent = 'Copied!';
    btn.classList.add('copied');
    setTimeout(function() { btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 2000);
  });
}

var homeCode = "import code\n\n# Types named 'Client' must be sealed\npredicate unsealed(Type) => Type.Name:endsWith('Client') && !isSealed\n\nforeach Code.Types:unsealed => PRINT('{Type.Name} should be sealed')";

function showHome() {
  var content = document.getElementById('content');
  content.innerHTML = `<h1>Cop Package Reference</h1>
  <div class="type-overview">
    <p><strong>Agent Cop</strong> is a static analysis tool that detects code slop &mdash; architectural violations, convention drift, and design debt that coding agents introduce at machine speed.</p>
    <p style="margin-top:8px;">Rules are expressed in a simple DSL and enforced deterministically in CI. Example:</p>
    <pre>${highlightCop(homeCode)}</pre>
    <p style="margin-top:12px;">Browse the package tree on the left to explore available types, predicates, functions, and commands.</p>
  </div>`;
  document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));
  if (location.hash) history.pushState(null, '', location.pathname);
}

// === ROUTING ===
function navigateToHash() {
  var hash = location.hash.replace(/^#/, '');
  if (!hash) { showHome(); return; }
  var parts = hash.split('/');
  var pkgId = parts[0];
  var target = parts[1] || null;
  if (!packages[pkgId]) { showHome(); return; }

  // Expand the package node in sidebar
  var pkgLabel = document.querySelector(`.tree-label[data-pkg="${pkgId}"]:not([data-type]):not([data-view]):not([data-section])`);
  if (pkgLabel) {
    var children = pkgLabel.nextElementSibling;
    if (children && children.classList.contains('collapsed')) {
      children.classList.remove('collapsed');
      var toggle = pkgLabel.querySelector('.tree-toggle');
      if (toggle) toggle.textContent = '▼';
    }
  }

  document.querySelectorAll('.tree-label.active').forEach(el => el.classList.remove('active'));

  if (!target) {
    renderPackageOverview(pkgId);
    if (pkgLabel) pkgLabel.classList.add('active');
  } else if (['predicates','functions','checks','commands','enums'].includes(target)) {
    if (target === 'predicates') renderFunctions(pkgId);
    else if (target === 'functions') renderFunctions(pkgId);
    else if (target === 'checks') renderChecks(pkgId);
    else if (target === 'commands') renderCommands(pkgId);
    else if (target === 'enums') renderEnums(pkgId);
    var viewLabel = document.querySelector(`.tree-label[data-pkg="${pkgId}"][data-view="${target}"]`);
    if (viewLabel) viewLabel.classList.add('active');
  } else {
    renderType(pkgId, target);
    var typeLabel = document.querySelector(`.tree-label[data-pkg="${pkgId}"][data-type="${target}"]`);
    if (typeLabel) typeLabel.classList.add('active');
  }
}

window.addEventListener('hashchange', navigateToHash);

// === INIT ===
buildTree();
updateBadge();
if (location.hash) navigateToHash();
else showHome();
</script>
</body>
</html>
""";
}
