using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Cop.Lang;
using Cop.Lang.Ast;
using Cop.Lang.Interpreter;

namespace CopMeta;

/// <summary>
/// Generates the editor metadata (<c>install/vscode-cop/metadata.json</c>) and the data-driven
/// parts of the TextMate grammar from cop's own authoritative definitions:
///   - types / enums / flags / predicates / functions: by loading the core packages with the
///     real cop parser (the same <see cref="ModuleLoader"/> the engine uses);
///   - keywords: from <see cref="Tokenizer.Keywords"/> + <see cref="LanguageMetadata"/>;
///   - primitive predicates / properties / transforms: from <see cref="LanguageMetadata"/>;
///   - available packages: by scanning the repo's <c>packages/</c> tree.
///
/// Nothing about the language is hand-maintained in the extension — it all flows from here, so a
/// drift test (regenerate + compare) keeps the committed files in lock-step with the language.
/// </summary>
public static class MetadataGenerator
{
    /// <summary>Packages whose declarations are bundled as always-available builtins.</summary>
    public static readonly string[] BundledPackages = ["code", "core"];

    public const string MetadataRelPath = "install/vscode-cop/metadata.json";
    public const string GrammarRelPath = "install/vscode-cop/syntaxes/cop.tmLanguage.json";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    // ── Public surface ──────────────────────────────────────────────────────

    /// <summary>Builds the metadata.json content for the repository at <paramref name="repoRoot"/>.</summary>
    public static string BuildMetadataJson(string repoRoot)
    {
        var packagesDir = Path.Combine(repoRoot, "packages");
        var modules = LoadModules(packagesDir, BundledPackages);

        var meta = new Metadata
        {
            Generated = "GENERATED by tools/copmeta from cop's C# definitions. Do not edit by hand.",
            Keywords = BuildKeywords(),
            Types = BuildTypes(modules),
            Predicates = BuildPredicates(modules),
            Functions = BuildFunctions(modules),
            Enums = BuildNamedLists<EnumDecl>(modules, d => d.Name, d => d.Members),
            Flags = BuildNamedLists<FlagsDecl>(modules, d => d.Name, d => d.Members),
            Primitives = BuildPrimitives(),
        };
        meta.Collections = BuildCollections(meta.Types);

        return JsonSerializer.Serialize(meta, JsonOptions) + "\n";
    }

    /// <summary>Injects the metadata-derived keyword/constant lists into an existing grammar file.</summary>
    public static string BuildGrammar(string existingGrammar)
    {
        var declaration = LanguageMetadata.Keywords.Where(k => k.Category == "declaration").Select(k => k.Name);
        var control = LanguageMetadata.Keywords.Where(k => k.Category == "control").Select(k => k.Name);
        var constants = LanguageMetadata.Keywords.Where(k => k.Category == "constant").Select(k => k.Name);

        var text = existingGrammar;
        text = ReplaceSectionMatch(text, "declaration-keywords", Alternation(declaration));
        text = ReplaceSectionMatch(text, "control-keywords", Alternation(control));
        text = ReplaceSectionMatch(text, "constants", Alternation(constants));
        return text;
    }

    /// <summary>
    /// Writes metadata.json and the regenerated grammar. When <paramref name="check"/> is true,
    /// only verifies they are up to date and returns non-zero (without writing) if not.
    /// </summary>
    public static int Run(string repoRoot, bool check)
    {
        var metaPath = Path.Combine(repoRoot, MetadataRelPath.Replace('/', Path.DirectorySeparatorChar));
        var grammarPath = Path.Combine(repoRoot, GrammarRelPath.Replace('/', Path.DirectorySeparatorChar));

        var newMeta = BuildMetadataJson(repoRoot);
        var newGrammar = BuildGrammar(File.ReadAllText(grammarPath));

        if (check)
        {
            var ok = true;
            if (Normalize(File.ReadAllText(metaPath)) != Normalize(newMeta))
            {
                Console.Error.WriteLine($"STALE: {MetadataRelPath} is out of date. Run: dotnet run --project tools/copmeta");
                ok = false;
            }
            if (Normalize(File.ReadAllText(grammarPath)) != Normalize(newGrammar))
            {
                Console.Error.WriteLine($"STALE: {GrammarRelPath} keyword lists are out of date. Run: dotnet run --project tools/copmeta");
                ok = false;
            }
            if (ok) Console.WriteLine("metadata.json and grammar are up to date.");
            return ok ? 0 : 1;
        }

        File.WriteAllText(metaPath, newMeta);
        File.WriteAllText(grammarPath, newGrammar);
        Console.WriteLine($"Wrote {MetadataRelPath}");
        Console.WriteLine($"Wrote {GrammarRelPath} (keyword lists)");
        return 0;
    }

    private static string Normalize(string s) => s.Replace("\r\n", "\n").TrimEnd('\n') + "\n";

    // ── Module loading ──────────────────────────────────────────────────────

    private static List<ModuleNode> LoadModules(string packagesDir, string[] packages)
    {
        var loader = new ModuleLoader([packagesDir]);
        var evaluator = new Evaluator();
        foreach (var pkg in packages)
            loader.LoadPackage(pkg, evaluator);
        return loader.LoadedModules.ToList();
    }

    private static IEnumerable<T> Decls<T>(IEnumerable<ModuleNode> modules) where T : Declaration =>
        modules.SelectMany(m => m.Declarations).OfType<T>();

    // ── Builders ────────────────────────────────────────────────────────────

    private static List<KeywordMeta> BuildKeywords()
    {
        // Tokenizer.Keywords is the authoritative set of keyword *names*; LanguageMetadata supplies
        // each one's detail + category. They must agree (asserted by a test); fall back gracefully.
        var info = LanguageMetadata.Keywords.ToDictionary(k => k.Name, StringComparer.Ordinal);
        var list = new List<KeywordMeta>();
        foreach (var name in Tokenizer.Keywords.Keys.OrderBy(n => n, StringComparer.Ordinal))
        {
            if (info.TryGetValue(name, out var k))
                list.Add(new KeywordMeta(k.Name, k.Detail, k.Category));
            else
                list.Add(new KeywordMeta(name, "keyword", "control"));
        }
        return list;
    }

    private static readonly HashSet<string> ExcludedTypeNames = new(StringComparer.Ordinal)
    {
        "object", "Object", "string", "int", "float", "bool", "byte", "bytes",
    };

    private static bool IsExcludedType(string name) =>
        ExcludedTypeNames.Contains(name)
        || name.StartsWith('[')          // generic placeholder like [T]
        || (name.Length == 1 && char.IsUpper(name[0])); // generic params T, R, K, A

    // A base type that is itself an excluded primitive (e.g. `object`) carries no useful
    // structure for the editor, so drop it rather than emit a dangling reference.
    private static string? NormalizeBase(string? baseName) =>
        baseName is not null && IsExcludedType(baseName) ? null : baseName;

    private static SortedDictionary<string, TypeMeta> BuildTypes(IEnumerable<ModuleNode> modules)
    {
        var result = new SortedDictionary<string, TypeMeta>(StringComparer.Ordinal);
        foreach (var td in Decls<TypeDecl>(modules))
        {
            // Primitive/generic types (string, int, [T], ...) are declared in core for the trait
            // system but are handled specially by the editor — never surface them as object types.
            if (IsExcludedType(td.Name)) continue;

            if (!result.TryGetValue(td.Name, out var tm))
            {
                tm = new TypeMeta { Base = NormalizeBase(td.BaseType), Properties = [] };
                result[td.Name] = tm;
            }
            else if (tm.Base is null && td.BaseType is not null)
            {
                tm.Base = NormalizeBase(td.BaseType);
            }

            foreach (var p in td.Properties)
            {
                // Skip computed/trait properties (e.g. `filePath => item.File.Path`) — they are
                // conformance mappings, not user-visible fields.
                if (p.ComputedExpr is not null) continue;
                if (tm.Properties.Any(existing => existing.Name == p.Name)) continue;
                tm.Properties.Add(new PropMeta(p.Name, TypeRefStr(p.Type, p.IsOptional)));
            }
        }
        return result;
    }

    private static SortedDictionary<string, string> BuildCollections(SortedDictionary<string, TypeMeta> types)
    {
        // The unified codebase model exposes its collections as collection-typed properties of the
        // Codebase type (Types -> [Type], Statements -> [Statement], ...). Surface those so bare and
        // qualified collection names resolve in the editor.
        var result = new SortedDictionary<string, string>(StringComparer.Ordinal);
        if (types.TryGetValue("Codebase", out var codebase))
        {
            foreach (var p in codebase.Properties)
            {
                if (p.Type.StartsWith('[') && p.Type.EndsWith(']'))
                    result[p.Name] = p.Type[1..^1];
            }
        }
        return result;
    }

    private static List<PredicateMeta> BuildPredicates(IEnumerable<ModuleNode> modules)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var list = new List<PredicateMeta>();
        foreach (var fd in Decls<FunctionDecl>(modules).Where(f => f.IsPredicate))
        {
            var paramType = fd.Params.Count > 0 ? TypeRefStr(fd.Params[0].Type, false) : "object";
            var returnType = fd.ReturnType?.Name;
            var key = $"{fd.Name}|{paramType}|{returnType}";
            if (seen.Add(key))
                list.Add(new PredicateMeta(fd.Name, paramType, returnType));
        }
        return list
            .OrderBy(p => p.Name, StringComparer.Ordinal)
            .ThenBy(p => p.ParamType, StringComparer.Ordinal)
            .ToList();
    }

    private static List<FunctionMeta> BuildFunctions(IEnumerable<ModuleNode> modules)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var list = new List<FunctionMeta>();

        foreach (var fd in Decls<FunctionDecl>(modules).Where(f => !f.IsPredicate && f.IsExported))
        {
            var paramStr = string.Join(", ", fd.Params.Select(FormatParam));
            var key = $"{fd.Name}|{paramStr}";
            if (seen.Add(key))
                list.Add(new FunctionMeta(fd.Name, paramStr, TypeRefStr(fd.ReturnType, false)));
        }
        // Commands (CHECK, METRICS, ...) are exported callables too.
        foreach (var cd in Decls<CommandDecl>(modules).Where(c => c.IsExported))
        {
            var paramStr = cd.Parameters is null ? "" : string.Join(", ", cd.Parameters);
            var key = $"{cd.Name}|{paramStr}";
            if (seen.Add(key))
                list.Add(new FunctionMeta(cd.Name, paramStr, null));
        }
        return list.OrderBy(f => f.Name, StringComparer.Ordinal).ThenBy(f => f.Params, StringComparer.Ordinal).ToList();
    }

    private static SortedDictionary<string, List<string>> BuildNamedLists<T>(
        IEnumerable<ModuleNode> modules, Func<T, string> name, Func<T, List<string>> members) where T : Declaration
    {
        var result = new SortedDictionary<string, List<string>>(StringComparer.Ordinal);
        foreach (var d in Decls<T>(modules))
            result[name(d)] = members(d);
        return result;
    }

    private static Primitives BuildPrimitives() => new()
    {
        StringPredicates = Map(LanguageMetadata.StringPredicates),
        NumericPredicates = Map(LanguageMetadata.NumericPredicates),
        CollectionPredicates = Map(LanguageMetadata.CollectionPredicates),
        UniversalPredicates = Map(LanguageMetadata.UniversalPredicates),
        ObjectPredicates = Map(LanguageMetadata.ObjectPredicates),
        StringProperties = Map(LanguageMetadata.StringProperties),
        StringTransforms = Map(LanguageMetadata.StringTransforms),
        CollectionProperties = Map(LanguageMetadata.CollectionProperties),
        CollectionTransforms = Map(LanguageMetadata.CollectionTransforms),
    };

    private static List<EntryMeta> Map(MetadataEntry[] entries) =>
        entries.Select(e => new EntryMeta(e.Name, e.Detail)).ToList();

    // ── Helpers ─────────────────────────────────────────────────────────────

    private static string TypeRefStr(TypeRef? t, bool optional)
    {
        if (t is null) return "object";
        var name = t.IsCollection ? $"[{t.Name}]" : t.Name;
        return optional && !t.IsCollection ? name + "?" : name;
    }

    private static string FormatParam(Parameter p) =>
        p.Type is null ? p.Name : $"{p.Name} : {TypeRefStr(p.Type, false)}";

    private static string Alternation(IEnumerable<string> names) =>
        @"\\b(" + string.Join("|", names) + @")\\b";

    /// <summary>Replaces the <c>"match"</c> value of the named grammar repository section.</summary>
    private static string ReplaceSectionMatch(string grammar, string sectionKey, string newMatch)
    {
        // Find: "sectionKey": { ... "match": "<value>"
        var sectionPattern = new Regex(
            "(\"" + Regex.Escape(sectionKey) + "\"\\s*:\\s*\\{[^}]*?\"match\"\\s*:\\s*\")(.*?)(\")",
            RegexOptions.Singleline);
        var m = sectionPattern.Match(grammar);
        if (!m.Success)
            throw new InvalidOperationException($"Grammar section '{sectionKey}' with a 'match' field not found.");
        return grammar[..m.Groups[2].Index] + newMatch + grammar[(m.Groups[2].Index + m.Groups[2].Length)..];
    }

    // ── Serialization model ─────────────────────────────────────────────────

    private sealed class Metadata
    {
        [JsonPropertyName("$generated")] public string Generated { get; set; } = "";
        public List<KeywordMeta> Keywords { get; set; } = [];
        public SortedDictionary<string, TypeMeta> Types { get; set; } = new(StringComparer.Ordinal);
        public SortedDictionary<string, string> Collections { get; set; } = new(StringComparer.Ordinal);
        public SortedDictionary<string, List<string>> Enums { get; set; } = new(StringComparer.Ordinal);
        public SortedDictionary<string, List<string>> Flags { get; set; } = new(StringComparer.Ordinal);
        public List<PredicateMeta> Predicates { get; set; } = [];
        public List<FunctionMeta> Functions { get; set; } = [];
        public Primitives Primitives { get; set; } = new();
    }

    private sealed class TypeMeta
    {
        public string? Base { get; set; }
        public List<PropMeta> Properties { get; set; } = [];
    }

    private sealed class Primitives
    {
        public List<EntryMeta> StringPredicates { get; set; } = [];
        public List<EntryMeta> NumericPredicates { get; set; } = [];
        public List<EntryMeta> CollectionPredicates { get; set; } = [];
        public List<EntryMeta> UniversalPredicates { get; set; } = [];
        public List<EntryMeta> ObjectPredicates { get; set; } = [];
        public List<EntryMeta> StringProperties { get; set; } = [];
        public List<EntryMeta> StringTransforms { get; set; } = [];
        public List<EntryMeta> CollectionProperties { get; set; } = [];
        public List<EntryMeta> CollectionTransforms { get; set; } = [];
    }

    private readonly record struct PropMeta(string Name, string Type);
    private readonly record struct EntryMeta(string Name, string Detail);
    private readonly record struct KeywordMeta(string Name, string Detail, string Category);
    private readonly record struct PredicateMeta(string Name, string ParamType, string? ReturnType);
    private readonly record struct FunctionMeta(string Name, string Params, string? ReturnType);
}
