<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\cop\cli\cop.csproj" />
    <ProjectReference Include="..\..\providers\csharp-provider\csharp-provider.csproj" />
    <ProjectReference Include="..\..\providers\python-provider\python-provider.csproj" />
    <ProjectReference Include="..\..\providers\javascript-provider\javascript-provider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="samples\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="referencetests\programs\**\*.cop" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\packages\code\src\code.cop" Link="samples\code.cop" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\packages\core\src\core.cop" Link="samples\core.cop" CopyToOutputDirectory="PreserveNewest" />
    <Compile Remove="samples\**\*.cs" />
  </ItemGroup>

</Project>
