using NUnit.Framework;
using Cop.Lang;
using CopMeta;

namespace Cop.Tests;

/// <summary>
/// Guards the VS Code extension's editor metadata against drift. The extension's IntelliSense and
/// colorizer are driven entirely by <c>install/vscode-cop/metadata.json</c> and the keyword lists
/// in the TextMate grammar, both generated by <c>tools/copmeta</c> from cop's own definitions.
///
/// If a change to the language (a new type/predicate/keyword/intrinsic, a renamed package, …) is
/// not reflected in the committed generated files, these tests fail with the exact command to fix
/// it. This is what stops the editor experience from silently breaking.
/// </summary>
[TestFixture]
public class EditorMetadataDriftTests
{
    private static string RepoRoot()
    {
        var dir = TestContext.CurrentContext.TestDirectory;
        while (dir is not null && !File.Exists(Path.Combine(dir, "cop.sln")))
            dir = Path.GetDirectoryName(dir);
        return dir ?? throw new InvalidOperationException("Could not find repo root (cop.sln)");
    }

    private static string Normalize(string s) => s.Replace("\r\n", "\n").TrimEnd('\n') + "\n";

    [Test]
    public void MetadataJson_is_in_sync_with_the_language()
    {
        var root = RepoRoot();
        var committedPath = Path.Combine(root, "install", "vscode-cop", "metadata.json");
        var committed = File.ReadAllText(committedPath);
        var regenerated = MetadataGenerator.BuildMetadataJson(root);

        Assert.That(Normalize(regenerated), Is.EqualTo(Normalize(committed)),
            "install/vscode-cop/metadata.json is stale. Regenerate with:\n" +
            "    dotnet run --project tools/copmeta");
    }

    [Test]
    public void Grammar_keyword_lists_are_in_sync_with_the_language()
    {
        var root = RepoRoot();
        var grammarPath = Path.Combine(root, "install", "vscode-cop", "syntaxes", "cop.tmLanguage.json");
        var committed = File.ReadAllText(grammarPath);
        // Re-injecting the metadata-derived keyword lists into the committed grammar must be a no-op.
        var regenerated = MetadataGenerator.BuildGrammar(committed);

        Assert.That(Normalize(regenerated), Is.EqualTo(Normalize(committed)),
            "Grammar keyword lists are stale. Regenerate with:\n" +
            "    dotnet run --project tools/copmeta");
    }

    [Test]
    public void LanguageMetadata_keywords_match_the_tokenizer()
    {
        // The tokenizer owns the set of keyword names; LanguageMetadata supplies their presentation.
        // They must describe exactly the same set, or generated keyword highlighting/completion drifts.
        var presented = LanguageMetadata.Keywords.Select(k => k.Name).OrderBy(n => n, StringComparer.Ordinal);
        var lexed = Tokenizer.Keywords.Keys.OrderBy(n => n, StringComparer.Ordinal);

        Assert.That(presented, Is.EqualTo(lexed),
            "LanguageMetadata.Keywords must list exactly the tokenizer's keywords.");
    }

    [Test]
    public void Generated_metadata_contains_the_core_violation_model()
    {
        // A focused sanity check on the bug that motivated this: the Violation type (and its full
        // property set) must be present so hovering a violation list never shows "unknown".
        var root = RepoRoot();
        var json = MetadataGenerator.BuildMetadataJson(root);
        using var doc = System.Text.Json.JsonDocument.Parse(json);
        var types = doc.RootElement.GetProperty("types");

        Assert.That(types.TryGetProperty("Violation", out var violation), Is.True,
            "metadata.json must define the Violation type.");
        var props = violation.GetProperty("properties").EnumerateArray()
            .Select(p => p.GetProperty("name").GetString()).ToHashSet();
        Assert.That(props, Does.Contain("Severity"));
        Assert.That(props, Does.Contain("Message"));
        Assert.That(props, Does.Contain("Check"));
    }
}
