using NUnit.Framework;
using Cop.Lang;
using CopMeta;

namespace Cop.Tests;

/// <summary>
/// Guards the VS Code extension's one generated file — the TextMate grammar — against drift. The
/// colorizer's keyword/constant lists in <c>syntaxes/cop.tmLanguage.json</c> are generated by
/// <c>tools/copmeta</c> from cop's own <see cref="LanguageMetadata"/>. (Live IntelliSense — hover,
/// completion, diagnostics — is served by <c>cop langserver</c> from the real compiler, so there is
/// no static metadata file to keep in sync.)
///
/// If a keyword/constant changes and the committed grammar isn't regenerated, this fails with the
/// exact command to fix it — stopping the colorizer from silently drifting from the language.
/// </summary>
[TestFixture]
public class EditorMetadataDriftTests
{
    private static string RepoRoot()
    {
        var dir = TestContext.CurrentContext.TestDirectory;
        while (dir is not null && !File.Exists(Path.Combine(dir, "cop.sln")))
            dir = Path.GetDirectoryName(dir);
        return dir ?? throw new InvalidOperationException("Could not find repo root (cop.sln)");
    }

    private static string Normalize(string s) => s.Replace("\r\n", "\n").TrimEnd('\n') + "\n";

    [Test]
    public void Grammar_keyword_lists_are_in_sync_with_the_language()
    {
        var root = RepoRoot();
        var grammarPath = Path.Combine(root, "install", "vscode-cop", "syntaxes", "cop.tmLanguage.json");
        var committed = File.ReadAllText(grammarPath);
        // Re-injecting the metadata-derived keyword lists into the committed grammar must be a no-op.
        var regenerated = MetadataGenerator.BuildGrammar(committed);

        Assert.That(Normalize(regenerated), Is.EqualTo(Normalize(committed)),
            "Grammar keyword lists are stale. Regenerate with:\n" +
            "    dotnet run --project tools/copmeta");
    }

    [Test]
    public void LanguageMetadata_keywords_match_the_tokenizer()
    {
        // The tokenizer owns the set of keyword names; LanguageMetadata supplies their presentation.
        // They must describe exactly the same set, or generated keyword highlighting drifts.
        var presented = LanguageMetadata.Keywords.Select(k => k.Name).OrderBy(n => n, StringComparer.Ordinal);
        var lexed = Tokenizer.Keywords.Keys.OrderBy(n => n, StringComparer.Ordinal);

        Assert.That(presented, Is.EqualTo(lexed),
            "LanguageMetadata.Keywords must list exactly the tokenizer's keywords.");
    }
}
